version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Path to the backend directory containing the Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data.db:/app/data.db  # Mount the SQLite database file

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    environment:
      - VITE_API_BASE_URL=http://backend:8000